name: 'Codespaces Key Sync'
description: 'Update Repo access for your codespaces keys en masse'
branding:
  icon: code
  color: green
inputs:
  # Recommended to store in your repo secrets as  CS_KEYS_PAT
  pat: 
    description: 'Personal Access Token  with codespaces and repo.read permissions'
    required: true
  # Organization you wish to query
  organization: 
    description: "Organization"
    required: true
  # CSV list of repos to allow key access to. (orgname/my-repo-one,)
  repos: 
    description: 'CSV list of repo IDs to include'
    required: false
    default: 'all'
  # CSV list of keys to update
  keys: 
    description: 'CSV list of keys to update'
    required: false
    default: all
  # Type of update to make. Update preserves existing, replace overwrites
  action: 
    description: "Update type"
    required: false
    default: 'update'

runs:
  using: 'node16'
  main: 'dist/index.js'
